/**
 * Generated by `payload generate:types`.
 * Run: pnpm payload generate:types (or npm run generate:types).
 * Requires DATABASE_URL and PAYLOAD_SECRET to be set.
 */
export interface User {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
