/**
 * Generated by `payload generate:types`.
 * Run: pnpm run generate:types (or after Phase 1: payload generate:types).
 * Requires DATABASE_URL and PAYLOAD_SECRET to be set.
 *
 * Until generate:types runs successfully, this file is hand-maintained for Phase 1 collections.
 */
export interface User {
  id: number;
  email: string;
  role: "admin" | "editor";
  updatedAt: string;
  createdAt: string;
}

export interface Media {
  id: number;
  filename: string;
  mimeType: string;
  filesize: number;
  width?: number;
  height?: number;
  updatedAt: string;
  createdAt: string;
  url?: string;
}

export interface Tag {
  id: number;
  name: string;
  slug: string;
  category?: "materials" | "systems" | "region" | "era" | "hazards";
  description?: string;
  content?: object;
  resources?: { label: string; url: string; type?: "link" | "youtube" | "guide" | "cost" }[];
  media?: (number | Media)[];
  updatedAt: string;
  createdAt: string;
}

export interface Listing {
  id: number;
  title: string;
  slug: string;
  address?: string;
  city?: string;
  state?: string;
  region?: string;
  yearBuilt?: number;
  price?: number;
  beds?: number;
  baths?: number;
  sqft?: number;
  garageSpaces?: number;
  summary?: string;
  sourceUrl?: string;
  photos?: (number | Media)[];
  tags?: (number | Tag)[];
  updatedAt: string;
  createdAt: string;
}
